// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_lear99.Models;

namespace Mission06_lear99.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230214040233_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_lear99.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Comedy",
                            Director = "John Landis",
                            Edited = false,
                            LentTo = "N/A",
                            Notes = "Potentially the greatest movie of all time!",
                            Rating = "PG",
                            Title = "The Three Amigos",
                            Year = 1986
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Action",
                            Director = "Guy Ritchie",
                            Edited = false,
                            LentTo = "N/A",
                            Notes = "A very fun spy movie with good russian!",
                            Rating = "PG-13",
                            Title = "The Man From U.N.C.L.E.",
                            Year = 2015
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Comedy",
                            Director = "Wes Anderson",
                            Edited = false,
                            LentTo = "N/A",
                            Notes = "Wes Anderson movies are amazing!",
                            Rating = "PG",
                            Title = "Fantastic Mr. Fox",
                            Year = 2009
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
